name: Build
on:
  workflow_run:
    workflows: ["Type Check"]
    types:
      - completed
jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout correct branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - run: echo "Building on ${{ github.event.workflow_run.head_branch }}"

