name: Type Check
on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed
jobs:
  type-check:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy step
        run: echo "🚀"
