name: Type Check
on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed
jobs:
  typecheck:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout correct branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - run: echo "Running typecheck on ${{ github.event.workflow_run.head_branch }}"
